### Multiple Linear Regression

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("economic_index.csv")

In [3]:
df.head()

   Unnamed: 0  year  month  interest_rate  unemployment_rate  index_price
0           0  2017     12           2.75                5.3         1464
1           1  2017     11           2.50                5.3         1394
2           2  2017     10           2.50                5.3         1357
3           3  2017      9           2.50                5.3         1293
4           4  2017      8           2.50                5.4         1256

In [4]:
df.drop(columns=['Unnamed: 0','year','month'],axis=1,inplace=True)

In [5]:
df

    interest_rate  unemployment_rate  index_price
0            2.75                5.3         1464
1            2.50                5.3         1394
2            2.50                5.3         1357
3            2.50                5.3         1293
4            2.50                5.4         1256
5            2.50                5.6         1254
6            2.50                5.5         1234
7            2.25                5.5         1195
8            2.25                5.5         1159
9            2.25                5.6         1167
10           2.00                5.7         1130
11           2.00                5.9         1075
12           2.00                6.0         1047
13           1.75                5.9          965
14           1.75                5.8          943
15           1.75                6.1          958
16           1.75                6.2          971
17           1.75                6.1          949
18           1.75                6.1          884
19           1.75                6.1          866
20           1.75                5.9          876
21           1.75                6.2          822
22           1.75                6.2          704
23           1.75                6.1          719

In [6]:
df.isnull().sum()

interest_rate        0
unemployment_rate    0
index_price          0
dtype: int64

In [7]:
df.corr()

                   interest_rate  unemployment_rate  index_price
interest_rate           1.000000          -0.925814     0.935793
unemployment_rate      -0.925814           1.000000    -0.922338
index_price             0.935793          -0.922338     1.000000

In [8]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [9]:
X

    interest_rate  unemployment_rate
0            2.75                5.3
1            2.50                5.3
2            2.50                5.3
3            2.50                5.3
4            2.50                5.4
5            2.50                5.6
6            2.50                5.5
7            2.25                5.5
8            2.25                5.5
9            2.25                5.6
10           2.00                5.7
11           2.00                5.9
12           2.00                6.0
13           1.75                5.9
14           1.75                5.8
15           1.75                6.1
16           1.75                6.2
17           1.75                6.1
18           1.75                6.1
19           1.75                6.1
20           1.75                5.9
21           1.75                6.2
22           1.75                6.2
23           1.75                6.1

In [10]:
y

0     1464
1     1394
2     1357
3     1293
4     1256
5     1254
6     1234
7     1195
8     1159
9     1167
10    1130
11    1075
12    1047
13     965
14     943
15     958
16     971
17     949
18     884
19     866
20     876
21     822
22     704
23     719
Name: index_price, dtype: int64

In [11]:
#Split the data into training data and test data
from sklearn.model_selection import train_test_split
X_Train,X_Test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

In [17]:
#Standardize the data
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_Train=scaler.fit_transform(X_Train)
X_Test=scaler.transform(X_Test)

In [18]:
#Train the model
from sklearn.linear_model import LinearRegression
regression=LinearRegression()
regression.fit(X_Train,y_train)

LinearRegression()

In [19]:
#Test the model
y_pred=regression.predict(X_Test)

In [20]:
#Performance measures
from sklearn.metrics import mean_absolute_error,mean_squared_error,root_mean_squared_error
mse=mean_squared_error(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
rmse=root_mean_squared_error(y_test,y_pred)

print("MSE: ",mse)
print("MAE: ",mae)
print("RMSE: ",rmse)

MSE:  5793.762887712579
MAE:  59.935781523235526
RMSE:  76.11677139574812

In [21]:
#Model accuracy
from sklearn.metrics import r2_score
model_accuracy=r2_score(y_test,y_pred)
print("Model Accurracy: ",model_accuracy)

Model Accurracy:  0.8278978091457142

In [22]:
intercept=regression.intercept_
coefficient=regression.coef_
print("Intercept: ",intercept)
print("Coefficient: ",coefficient)

Intercept:  1053.4444444444443
Coefficient:  [  88.27275507 -116.25716066]

### OLS

In [23]:
import statsmodels.api as sm

In [24]:
model=sm.OLS(X_Train,y_train).fit()